[toolchain]

[build]
solana-version = "1.18.0"
rust-compiler = "/home/m/.cargo/bin/rustc"


[features]
resolution = true
skip-lint = true

[programs.localnet]
borrow = "DwkmwaYRJe3VUzj5Yyb2VK34kr2sGUBFH1HU6MjMHGPY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/m/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

